-- Script para crear el esquema Oracle para el sistema de formularios dinámicos
-- Esquema: IDO_FORMULARIO
-- Usuario: IDO_FORMULARIO
-- Clave: MFLstcIII4#
--
-- IMPORTANTE: Este script debe ejecutarse conectado como el usuario IDO_FORMULARIO
-- Ejemplo de conexión:
--   sqlplus IDO_FORMULARIO/MFLstcIII4#@192.168.125.181:1521/juntosdv
--   @create_formularios_schema.sql
--
-- Las tablas se crearán automáticamente en el esquema IDO_FORMULARIO
-- y las consultas en el código usarán el prefijo IDO_FORMULARIO. para acceder a ellas

-- ============================================
-- SECUENCIAS
-- ============================================

-- Secuencia para formularios
CREATE SEQUENCE IDO_FORMULARIO.CBSE_FORMULARIOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para secciones
CREATE SEQUENCE IDO_FORMULARIO.CBSE_SECCIONES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para campos
CREATE SEQUENCE IDO_FORMULARIO.CBSE_CAMPOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para opciones de campos
CREATE SEQUENCE IDO_FORMULARIO.CBSE_OPCIONES_CAMPOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para respuestas
CREATE SEQUENCE IDO_FORMULARIO.CBSE_RESPUESTAS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para valores de respuestas
CREATE SEQUENCE IDO_FORMULARIO.CBSE_RESPUESTA_VALORES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para borradores
CREATE SEQUENCE IDO_FORMULARIO.CBSE_BORRADORES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para valores de borradores
CREATE SEQUENCE IDO_FORMULARIO.CBSE_BORRADOR_VALORES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- ============================================
-- TABLAS
-- ============================================

-- Tabla de formularios
CREATE TABLE IDO_FORMULARIO.CBTC_FORMULARIOS (
    ID_FORMULARIO NUMBER DEFAULT IDO_FORMULARIO.CBSE_FORMULARIOS.NEXTVAL PRIMARY KEY,
    NO_TITULO VARCHAR2(200) NOT NULL,
    DE_DESCRIPCION VARCHAR2(1000),
    CO_ESTADO VARCHAR2(20) DEFAULT 'BORRADOR' NOT NULL, -- BORRADOR, PUBLICADO, CERRADO
    CO_CATEGORIA VARCHAR2(100),
    ID_USUARIO_CREADOR NUMBER NOT NULL, -- FK a CBTC_USUARIOS
    FE_INICIO DATE, -- Fecha de inicio de disponibilidad
    FE_FIN DATE, -- Fecha de fin de disponibilidad
    FE_CREACION DATE DEFAULT SYSDATE NOT NULL,
    FE_ACTUALIZACION DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CHK_ESTADO_FORMULARIO CHECK (CO_ESTADO IN ('BORRADOR', 'PUBLICADO', 'CERRADO')),
    CONSTRAINT CHK_FECHAS_FORMULARIO CHECK (FE_FIN IS NULL OR FE_INICIO IS NULL OR FE_FIN >= FE_INICIO)
);

-- Tabla de secciones (sesiones) del formulario
CREATE TABLE IDO_FORMULARIO.CBTC_SECCIONES (
    ID_SECCION NUMBER DEFAULT IDO_FORMULARIO.CBSE_SECCIONES.NEXTVAL PRIMARY KEY,
    ID_FORMULARIO NUMBER NOT NULL, -- FK a CBTC_FORMULARIOS
    NO_TITULO VARCHAR2(200) NOT NULL,
    DE_DESCRIPCION VARCHAR2(500),
    NU_ORDEN NUMBER NOT NULL, -- Orden de la sección en el formulario
    FE_CREACION DATE DEFAULT SYSDATE NOT NULL,
    FE_ACTUALIZACION DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_SECCION_FORMULARIO FOREIGN KEY (ID_FORMULARIO) 
        REFERENCES IDO_FORMULARIO.CBTC_FORMULARIOS(ID_FORMULARIO) ON DELETE CASCADE
);

-- Tabla de campos del formulario
CREATE TABLE IDO_FORMULARIO.CBTC_CAMPOS (
    ID_CAMPO NUMBER DEFAULT IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL PRIMARY KEY,
    ID_SECCION NUMBER NOT NULL, -- FK a CBTC_SECCIONES
    CO_TIPO VARCHAR2(50) NOT NULL, -- TEXTO_CORTO, TEXTO_LARGO, SELECCION, OPCION_UNICA, OPCION_MULTIPLE, FECHA, NUMERO, EMAIL
    NO_LABEL VARCHAR2(200) NOT NULL,
    DE_PLACEHOLDER VARCHAR2(200),
    DE_VALOR_DEFECTO VARCHAR2(500),
    DE_AYUDA VARCHAR2(500),
    NU_ORDEN NUMBER NOT NULL, -- Orden del campo en la sección
    FL_OBLIGATORIO CHAR(1) DEFAULT 'N' NOT NULL, -- S/N
    FL_ACTIVO CHAR(1) DEFAULT 'S' NOT NULL, -- S/N
    -- Validaciones
    NU_MIN_CARACTERES NUMBER,
    NU_MAX_CARACTERES NUMBER,
    DE_PATRON_REGEX VARCHAR2(500), -- Patrón regex opcional
    NU_MIN_VALOR NUMBER, -- Para campos numéricos
    NU_MAX_VALOR NUMBER, -- Para campos numéricos
    FL_TIENE_OTRO CHAR(1) DEFAULT 'N' NOT NULL, -- S/N - Si tiene opción "Otro" con texto libre
    FE_CREACION DATE DEFAULT SYSDATE NOT NULL,
    FE_ACTUALIZACION DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_CAMPO_SECCION FOREIGN KEY (ID_SECCION) 
        REFERENCES IDO_FORMULARIO.CBTC_SECCIONES(ID_SECCION) ON DELETE CASCADE,
    CONSTRAINT CHK_TIPO_CAMPO CHECK (CO_TIPO IN ('TEXTO_CORTO', 'TEXTO_LARGO', 'SELECCION', 'OPCION_UNICA', 'OPCION_MULTIPLE', 'FECHA', 'NUMERO', 'EMAIL')),
    CONSTRAINT CHK_OBLIGATORIO CHECK (FL_OBLIGATORIO IN ('S', 'N')),
    CONSTRAINT CHK_ACTIVO CHECK (FL_ACTIVO IN ('S', 'N')),
    CONSTRAINT CHK_TIENE_OTRO CHECK (FL_TIENE_OTRO IN ('S', 'N'))
);

-- Tabla de opciones para campos de tipo SELECCION, OPCION_UNICA, OPCION_MULTIPLE
CREATE TABLE IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (
    ID_OPCION NUMBER DEFAULT IDO_FORMULARIO.CBSE_OPCIONES_CAMPOS.NEXTVAL PRIMARY KEY,
    ID_CAMPO NUMBER NOT NULL, -- FK a CBTC_CAMPOS
    NO_TEXTO VARCHAR2(200) NOT NULL, -- Texto visible de la opción
    DE_VALOR VARCHAR2(200), -- Valor de la opción (puede ser diferente del texto)
    NU_ORDEN NUMBER NOT NULL, -- Orden de la opción
    FE_CREACION DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_OPCION_CAMPO FOREIGN KEY (ID_CAMPO) 
        REFERENCES IDO_FORMULARIO.CBTC_CAMPOS(ID_CAMPO) ON DELETE CASCADE
);

-- Tabla de respuestas (una respuesta por usuario por formulario)
CREATE TABLE IDO_FORMULARIO.CBTC_RESPUESTAS (
    ID_RESPUESTA NUMBER DEFAULT IDO_FORMULARIO.CBSE_RESPUESTAS.NEXTVAL PRIMARY KEY,
    ID_FORMULARIO NUMBER NOT NULL, -- FK a CBTC_FORMULARIOS
    ID_USUARIO NUMBER NOT NULL, -- FK a CBTC_USUARIOS (quien responde)
    CO_ESTADO VARCHAR2(20) DEFAULT 'BORRADOR' NOT NULL, -- BORRADOR, COMPLETADO
    FE_INICIO DATE DEFAULT SYSDATE NOT NULL, -- Fecha de inicio de respuesta
    FE_ULTIMA_ACTUALIZACION DATE DEFAULT SYSDATE NOT NULL, -- Para sincronización
    FE_ENVIO DATE, -- Fecha de envío (cuando se completa)
    FE_CREACION DATE DEFAULT SYSDATE NOT NULL,
    FE_ACTUALIZACION DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_RESPUESTA_FORMULARIO FOREIGN KEY (ID_FORMULARIO) 
        REFERENCES IDO_FORMULARIO.CBTC_FORMULARIOS(ID_FORMULARIO) ON DELETE CASCADE,
    CONSTRAINT CHK_ESTADO_RESPUESTA CHECK (CO_ESTADO IN ('BORRADOR', 'COMPLETADO'))
);

-- Tabla de valores de respuestas (los valores respondidos para cada campo)
CREATE TABLE IDO_FORMULARIO.CBTC_RESPUESTA_VALORES (
    ID_VALOR NUMBER DEFAULT IDO_FORMULARIO.CBSE_RESPUESTA_VALORES.NEXTVAL PRIMARY KEY,
    ID_RESPUESTA NUMBER NOT NULL, -- FK a CBTC_RESPUESTAS
    ID_CAMPO NUMBER NOT NULL, -- FK a CBTC_CAMPOS
    DE_VALOR_TEXTO CLOB, -- Para valores de texto
    NU_VALOR_NUMERO NUMBER, -- Para valores numéricos
    FE_VALOR_FECHA DATE, -- Para valores de fecha
    ID_OPCION_SELECCIONADA NUMBER, -- FK a CBTC_OPCIONES_CAMPOS (para opciones seleccionadas)
    DE_TEXTO_OTRO VARCHAR2(500), -- Texto libre cuando se selecciona "Otro"
    FE_CREACION DATE DEFAULT SYSDATE NOT NULL,
    FE_ACTUALIZACION DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_VALOR_RESPUESTA FOREIGN KEY (ID_RESPUESTA) 
        REFERENCES IDO_FORMULARIO.CBTC_RESPUESTAS(ID_RESPUESTA) ON DELETE CASCADE,
    CONSTRAINT FK_VALOR_CAMPO FOREIGN KEY (ID_CAMPO) 
        REFERENCES IDO_FORMULARIO.CBTC_CAMPOS(ID_CAMPO) ON DELETE CASCADE,
    CONSTRAINT FK_VALOR_OPCION FOREIGN KEY (ID_OPCION_SELECCIONADA) 
        REFERENCES IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS(ID_OPCION) ON DELETE SET NULL
);

-- Tabla de borradores temporales (guardado temporal antes de enviar)
CREATE TABLE IDO_FORMULARIO.CBTC_BORRADORES (
    ID_BORRADOR NUMBER DEFAULT IDO_FORMULARIO.CBSE_BORRADORES.NEXTVAL PRIMARY KEY,
    ID_FORMULARIO NUMBER NOT NULL, -- FK a CBTC_FORMULARIOS
    ID_USUARIO NUMBER NOT NULL, -- FK a CBTC_USUARIOS
    FE_INICIO DATE DEFAULT SYSDATE NOT NULL,
    FE_ULTIMA_ACTUALIZACION DATE DEFAULT SYSDATE NOT NULL,
    FE_CREACION DATE DEFAULT SYSDATE NOT NULL,
    FE_ACTUALIZACION DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_BORRADOR_FORMULARIO FOREIGN KEY (ID_FORMULARIO) 
        REFERENCES IDO_FORMULARIO.CBTC_FORMULARIOS(ID_FORMULARIO) ON DELETE CASCADE,
    CONSTRAINT UK_BORRADOR_USUARIO_FORMULARIO UNIQUE (ID_FORMULARIO, ID_USUARIO) -- Un borrador por usuario por formulario
);

-- Tabla de valores de borradores (valores guardados temporalmente)
CREATE TABLE IDO_FORMULARIO.CBTC_BORRADOR_VALORES (
    ID_VALOR NUMBER DEFAULT IDO_FORMULARIO.CBSE_BORRADOR_VALORES.NEXTVAL PRIMARY KEY,
    ID_BORRADOR NUMBER NOT NULL, -- FK a CBTC_BORRADORES
    ID_CAMPO NUMBER NOT NULL, -- FK a CBTC_CAMPOS
    DE_VALOR_TEXTO CLOB,
    NU_VALOR_NUMERO NUMBER,
    FE_VALOR_FECHA DATE,
    ID_OPCION_SELECCIONADA NUMBER, -- FK a CBTC_OPCIONES_CAMPOS
    DE_TEXTO_OTRO VARCHAR2(500),
    FE_CREACION DATE DEFAULT SYSDATE NOT NULL,
    FE_ACTUALIZACION DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_BORRADOR_VALOR_BORRADOR FOREIGN KEY (ID_BORRADOR) 
        REFERENCES IDO_FORMULARIO.CBTC_BORRADORES(ID_BORRADOR) ON DELETE CASCADE,
    CONSTRAINT FK_BORRADOR_VALOR_CAMPO FOREIGN KEY (ID_CAMPO) 
        REFERENCES IDO_FORMULARIO.CBTC_CAMPOS(ID_CAMPO) ON DELETE CASCADE,
    CONSTRAINT FK_BORRADOR_VALOR_OPCION FOREIGN KEY (ID_OPCION_SELECCIONADA) 
        REFERENCES IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS(ID_OPCION) ON DELETE SET NULL
);

-- ============================================
-- ÍNDICES
-- ============================================

-- Índices para mejorar performance en búsquedas frecuentes
CREATE INDEX IDO_FORMULARIO.IDX_FORMULARIOS_ESTADO ON IDO_FORMULARIO.CBTC_FORMULARIOS(CO_ESTADO);
CREATE INDEX IDO_FORMULARIO.IDX_FORMULARIOS_CREADOR ON IDO_FORMULARIO.CBTC_FORMULARIOS(ID_USUARIO_CREADOR);
CREATE INDEX IDO_FORMULARIO.IDX_FORMULARIOS_FECHAS ON IDO_FORMULARIO.CBTC_FORMULARIOS(FE_INICIO, FE_FIN);
CREATE INDEX IDO_FORMULARIO.IDX_FORMULARIOS_ACTUALIZACION ON IDO_FORMULARIO.CBTC_FORMULARIOS(FE_ACTUALIZACION);

CREATE INDEX IDO_FORMULARIO.IDX_SECCIONES_FORMULARIO ON IDO_FORMULARIO.CBTC_SECCIONES(ID_FORMULARIO);
CREATE INDEX IDO_FORMULARIO.IDX_SECCIONES_ORDEN ON IDO_FORMULARIO.CBTC_SECCIONES(ID_FORMULARIO, NU_ORDEN);

CREATE INDEX IDO_FORMULARIO.IDX_CAMPOS_SECCION ON IDO_FORMULARIO.CBTC_CAMPOS(ID_SECCION);
CREATE INDEX IDO_FORMULARIO.IDX_CAMPOS_ORDEN ON IDO_FORMULARIO.CBTC_CAMPOS(ID_SECCION, NU_ORDEN);
CREATE INDEX IDO_FORMULARIO.IDX_CAMPOS_TIPO ON IDO_FORMULARIO.CBTC_CAMPOS(CO_TIPO);

CREATE INDEX IDO_FORMULARIO.IDX_OPCIONES_CAMPO ON IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS(ID_CAMPO);
CREATE INDEX IDO_FORMULARIO.IDX_OPCIONES_ORDEN ON IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS(ID_CAMPO, NU_ORDEN);

CREATE INDEX IDO_FORMULARIO.IDX_RESPUESTAS_FORMULARIO ON IDO_FORMULARIO.CBTC_RESPUESTAS(ID_FORMULARIO);
CREATE INDEX IDO_FORMULARIO.IDX_RESPUESTAS_USUARIO ON IDO_FORMULARIO.CBTC_RESPUESTAS(ID_USUARIO);
CREATE INDEX IDO_FORMULARIO.IDX_RESPUESTAS_ESTADO ON IDO_FORMULARIO.CBTC_RESPUESTAS(CO_ESTADO);
CREATE INDEX IDO_FORMULARIO.IDX_RESPUESTAS_ACTUALIZACION ON IDO_FORMULARIO.CBTC_RESPUESTAS(FE_ACTUALIZACION);

CREATE INDEX IDO_FORMULARIO.IDX_RESPUESTA_VALORES_RESPUESTA ON IDO_FORMULARIO.CBTC_RESPUESTA_VALORES(ID_RESPUESTA);
CREATE INDEX IDO_FORMULARIO.IDX_RESPUESTA_VALORES_CAMPO ON IDO_FORMULARIO.CBTC_RESPUESTA_VALORES(ID_CAMPO);

CREATE INDEX IDO_FORMULARIO.IDX_BORRADORES_USUARIO ON IDO_FORMULARIO.CBTC_BORRADORES(ID_USUARIO);
CREATE INDEX IDO_FORMULARIO.IDX_BORRADORES_FORMULARIO ON IDO_FORMULARIO.CBTC_BORRADORES(ID_FORMULARIO);
CREATE INDEX IDO_FORMULARIO.IDX_BORRADORES_ACTUALIZACION ON IDO_FORMULARIO.CBTC_BORRADORES(FE_ACTUALIZACION);

CREATE INDEX IDO_FORMULARIO.IDX_BORRADOR_VALORES_BORRADOR ON IDO_FORMULARIO.CBTC_BORRADOR_VALORES(ID_BORRADOR);
CREATE INDEX IDO_FORMULARIO.IDX_BORRADOR_VALORES_CAMPO ON IDO_FORMULARIO.CBTC_BORRADOR_VALORES(ID_CAMPO);

-- ============================================
-- TRIGGERS
-- ============================================

-- Trigger para actualizar FE_ACTUALIZACION en CBTC_FORMULARIOS
CREATE OR REPLACE TRIGGER IDO_FORMULARIO.TRG_FORMULARIOS_ACTUALIZACION
BEFORE UPDATE ON IDO_FORMULARIO.CBTC_FORMULARIOS
FOR EACH ROW
BEGIN
    :NEW.FE_ACTUALIZACION := SYSDATE;
END;
/

-- Trigger para actualizar FE_ACTUALIZACION en CBTC_SECCIONES
CREATE OR REPLACE TRIGGER IDO_FORMULARIO.TRG_SECCIONES_ACTUALIZACION
BEFORE UPDATE ON IDO_FORMULARIO.CBTC_SECCIONES
FOR EACH ROW
BEGIN
    :NEW.FE_ACTUALIZACION := SYSDATE;
END;
/

-- Trigger para actualizar FE_ACTUALIZACION en CBTC_CAMPOS
CREATE OR REPLACE TRIGGER IDO_FORMULARIO.TRG_CAMPOS_ACTUALIZACION
BEFORE UPDATE ON IDO_FORMULARIO.CBTC_CAMPOS
FOR EACH ROW
BEGIN
    :NEW.FE_ACTUALIZACION := SYSDATE;
END;
/

-- Trigger para actualizar FE_ACTUALIZACION en CBTC_RESPUESTAS
CREATE OR REPLACE TRIGGER IDO_FORMULARIO.TRG_RESPUESTAS_ACTUALIZACION
BEFORE UPDATE ON IDO_FORMULARIO.CBTC_RESPUESTAS
FOR EACH ROW
BEGIN
    :NEW.FE_ACTUALIZACION := SYSDATE;
    :NEW.FE_ULTIMA_ACTUALIZACION := SYSDATE;
END;
/

-- Trigger para actualizar FE_ACTUALIZACION en CBTC_RESPUESTA_VALORES
CREATE OR REPLACE TRIGGER IDO_FORMULARIO.TRG_RESPUESTA_VALORES_ACTUALIZACION
BEFORE UPDATE ON IDO_FORMULARIO.CBTC_RESPUESTA_VALORES
FOR EACH ROW
BEGIN
    :NEW.FE_ACTUALIZACION := SYSDATE;
END;
/

-- Trigger para actualizar FE_ACTUALIZACION en CBTC_BORRADORES
CREATE OR REPLACE TRIGGER IDO_FORMULARIO.TRG_BORRADORES_ACTUALIZACION
BEFORE UPDATE ON IDO_FORMULARIO.CBTC_BORRADORES
FOR EACH ROW
BEGIN
    :NEW.FE_ACTUALIZACION := SYSDATE;
    :NEW.FE_ULTIMA_ACTUALIZACION := SYSDATE;
END;
/

-- Trigger para actualizar FE_ACTUALIZACION en CBTC_BORRADOR_VALORES
CREATE OR REPLACE TRIGGER IDO_FORMULARIO.TRG_BORRADOR_VALORES_ACTUALIZACION
BEFORE UPDATE ON IDO_FORMULARIO.CBTC_BORRADOR_VALORES
FOR EACH ROW
BEGIN
    :NEW.FE_ACTUALIZACION := SYSDATE;
END;
/

COMMIT;

-- ============================================
-- VERIFICACIÓN
-- ============================================

SELECT 'Secuencia IDO_FORMULARIO.CBSE_FORMULARIOS creada' AS mensaje FROM DUAL;
SELECT 'Secuencia IDO_FORMULARIO.CBSE_SECCIONES creada' AS mensaje FROM DUAL;
SELECT 'Secuencia IDO_FORMULARIO.CBSE_CAMPOS creada' AS mensaje FROM DUAL;
SELECT 'Secuencia IDO_FORMULARIO.CBSE_OPCIONES_CAMPOS creada' AS mensaje FROM DUAL;
SELECT 'Secuencia IDO_FORMULARIO.CBSE_RESPUESTAS creada' AS mensaje FROM DUAL;
SELECT 'Secuencia IDO_FORMULARIO.CBSE_RESPUESTA_VALORES creada' AS mensaje FROM DUAL;
SELECT 'Secuencia IDO_FORMULARIO.CBSE_BORRADORES creada' AS mensaje FROM DUAL;
SELECT 'Secuencia IDO_FORMULARIO.CBSE_BORRADOR_VALORES creada' AS mensaje FROM DUAL;

SELECT 'Tabla IDO_FORMULARIO.CBTC_FORMULARIOS creada' AS mensaje FROM DUAL;
SELECT 'Tabla IDO_FORMULARIO.CBTC_SECCIONES creada' AS mensaje FROM DUAL;
SELECT 'Tabla IDO_FORMULARIO.CBTC_CAMPOS creada' AS mensaje FROM DUAL;
SELECT 'Tabla IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS creada' AS mensaje FROM DUAL;
SELECT 'Tabla IDO_FORMULARIO.CBTC_RESPUESTAS creada' AS mensaje FROM DUAL;
SELECT 'Tabla IDO_FORMULARIO.CBTC_RESPUESTA_VALORES creada' AS mensaje FROM DUAL;
SELECT 'Tabla IDO_FORMULARIO.CBTC_BORRADORES creada' AS mensaje FROM DUAL;
SELECT 'Tabla IDO_FORMULARIO.CBTC_BORRADOR_VALORES creada' AS mensaje FROM DUAL;

SELECT 'Índices creados exitosamente' AS mensaje FROM DUAL;
SELECT 'Triggers creados exitosamente' AS mensaje FROM DUAL;

SELECT '✅ Esquema de formularios creado exitosamente' AS mensaje FROM DUAL;

