-- Script para crear el formulario: FORMATO Nº1 - FICHA DE VISITA DOMICILIARIA Nº1 Y REGISTRO DE DATOS DEL PARTICIPANTE
-- IMPORTANTE: Asegúrate de tener un usuario creador válido (ID_USUARIO_CREADOR)
-- Por defecto usa el usuario ID 1, ajusta según corresponda

SET SERVEROUTPUT ON;

DECLARE
    v_form_id NUMBER;
    v_seccion_id NUMBER;
    v_campo_id NUMBER;
    v_opcion_id NUMBER;
    v_usuario_creador NUMBER := 1; -- Cambiar según el ID del usuario administrador
    v_form_existente_id NUMBER;
BEGIN
    -- ========== ELIMINAR FORMULARIO SI YA EXISTE ==========
    BEGIN
        SELECT ID_FORMULARIO INTO v_form_existente_id
        FROM IDO_FORMULARIO.CBTC_FORMULARIOS
        WHERE NO_TITULO = 'FORMATO Nº1 - FICHA DE VISITA DOMICILIARIA Nº1 Y REGISTRO DE DATOS DEL PARTICIPANTE'
        AND ROWNUM = 1;
        
        IF v_form_existente_id IS NOT NULL THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ Formulario existente encontrado con ID: ' || v_form_existente_id);
            DBMS_OUTPUT.PUT_LINE('🗑️ Eliminando formulario existente...');
            
            -- Eliminar formulario (las FK con CASCADE eliminarán secciones, campos y opciones)
            DELETE FROM IDO_FORMULARIO.CBTC_FORMULARIOS 
            WHERE ID_FORMULARIO = v_form_existente_id;
            
            COMMIT; -- Confirmar la eliminación
            
            DBMS_OUTPUT.PUT_LINE('✅ Formulario eliminado correctamente');
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('ℹ️ No se encontró formulario existente, se creará uno nuevo');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ Error al verificar formulario existente: ' || SQLERRM);
            -- Continuar con la creación aunque haya error al verificar
    END;
    
    -- ========== CREAR FORMULARIO ==========
    INSERT INTO IDO_FORMULARIO.CBTC_FORMULARIOS (
        ID_FORMULARIO, NO_TITULO, DE_DESCRIPCION, CO_ESTADO, CO_CATEGORIA, 
        ID_USUARIO_CREADOR, FE_INICIO, FE_FIN, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_FORMULARIOS.NEXTVAL, 
        'FORMATO Nº1 - FICHA DE VISITA DOMICILIARIA Nº1 Y REGISTRO DE DATOS DEL PARTICIPANTE', 
        'Formulario para registro de datos del participante en el programa educativo Juntos',
        'PUBLICADO', 
        'VISITA_DOMICILIARIA',
        v_usuario_creador,
        SYSDATE, 
        NULL, 
        SYSDATE, 
        SYSDATE
    )
    RETURNING ID_FORMULARIO INTO v_form_id;

    DBMS_OUTPUT.PUT_LINE('✅ Formulario creado con ID: ' || v_form_id);

    -- ========== SECCIÓN 0: DATOS DEL PARTICIPANTE ==========
    INSERT INTO IDO_FORMULARIO.CBTC_SECCIONES (
        ID_SECCION, ID_FORMULARIO, NO_TITULO, DE_DESCRIPCION, NU_ORDEN, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_SECCIONES.NEXTVAL,
        v_form_id,
        'Datos del Participante',
        'Información básica del gestor local y datos de aplicación',
        0,
        SYSDATE,
        SYSDATE
    )
    RETURNING ID_SECCION INTO v_seccion_id;

    DBMS_OUTPUT.PUT_LINE('✅ Sección 0 (Datos del Participante) creada con ID: ' || v_seccion_id);

    -- Campo: Fecha de aplicación
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'FECHA', 'Fecha de aplicación', 
        'Seleccione la fecha', 1, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    -- Campo: DNI Gestor Local
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, NU_MIN_CARACTERES, NU_MAX_CARACTERES, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'TEXTO_CORTO', 'DNI Gestor Local', 
        'Ingrese el DNI', 2, 'S', 'S', 8, 8, SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    -- Campo: Nombre y apellidos del Gestor Local
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, NU_MIN_CARACTERES, NU_MAX_CARACTERES, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'TEXTO_CORTO', 'Nombre y apellidos del Gestor Local', 
        'Ingrese nombre completo', 3, 'S', 'S', 3, 200, SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    -- Campo: Unidad Territorial
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'TEXTO_CORTO', 'Unidad Territorial', 
        'Ingrese unidad territorial', 4, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    -- Campo: Provincia
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'TEXTO_CORTO', 'Provincia', 
        'Ingrese provincia', 5, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    -- Campo: Distrito
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'TEXTO_CORTO', 'Distrito', 
        'Ingrese distrito', 6, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    -- Campo: Código de Hogar del MO
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'TEXTO_CORTO', 'Código de Hogar del MO', 
        'Ingrese código', 7, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    -- Campo: Tipo de incentivo Juntos
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'TEXTO_CORTO', 'Tipo de incentivo Juntos', 
        'Ingrese tipo de incentivo', 8, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    -- ========== SECCIÓN I: DATOS PERSONALES DEL PARTICIPANTE ==========
    INSERT INTO IDO_FORMULARIO.CBTC_SECCIONES (
        ID_SECCION, ID_FORMULARIO, NO_TITULO, DE_DESCRIPCION, NU_ORDEN, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_SECCIONES.NEXTVAL,
        v_form_id,
        'I. DATOS PERSONALES DEL PARTICIPANTE PROGRAMA EDUCATIVO (madre/cuidador o gestante)',
        'Información personal del participante',
        1,
        SYSDATE,
        SYSDATE
    )
    RETURNING ID_SECCION INTO v_seccion_id;

    DBMS_OUTPUT.PUT_LINE('✅ Sección I creada con ID: ' || v_seccion_id);

    -- Campo 1: Documento de identidad del MH participante (DNI/CE)
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, NU_MIN_CARACTERES, NU_MAX_CARACTERES, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'TEXTO_CORTO', 
        'Documento de identidad del MH participante (DNI/CE)', 'Ingrese DNI o CE', 1, 'S', 'S', 8, 12, SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    -- Campo 2: Nombres y apellidos completos
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, NU_MIN_CARACTERES, NU_MAX_CARACTERES, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'TEXTO_CORTO', 
        'Nombres y apellidos completos', 'Ingrese nombres completos', 2, 'S', 'S', 3, 200, SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    -- Campo 3: Edad
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, NU_MIN_VALOR, NU_MAX_VALOR, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'NUMERO', 
        'Edad', 'Ingrese edad', 3, 'S', 'S', 1, 120, SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    -- Campo 4: Condición actual (OPCION_UNICA)
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_UNICA', 
        'Condición actual', 'Seleccione condición', 4, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) 
    VALUES (v_campo_id, 'Gestante (número de semanas: ___)', 'GESTANTE', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) 
    VALUES (v_campo_id, 'Edad del niño/a menor de 2 años: ___ meses', 'MENOR_2_ANOS', 2, SYSDATE);

    -- Campo 5: Teléfono de contacto y WhatsApp
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, NU_MIN_CARACTERES, NU_MAX_CARACTERES, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'TEXTO_CORTO', 
        'Teléfono de contacto', 'Ingrese teléfono', 5, 'N', 'S', 9, 15, SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    -- Campo: Tiene acceso WhatsApp (OPCION_UNICA)
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_UNICA', 
        'Tiene acceso WhatsApp', 'Seleccione', 6, 'N', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) 
    VALUES (v_campo_id, 'SI', 'SI', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) 
    VALUES (v_campo_id, 'NO', 'NO', 2, SYSDATE);

    -- Campo 6: ¿Se identifica con alguna comunidad indígena o campesina?
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FL_TIENE_OTRO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_UNICA', 
        '¿Se identifica con alguna comunidad indígena o campesina?', 'Seleccione', 7, 'S', 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) 
    VALUES (v_campo_id, 'Sí', 'SI', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) 
    VALUES (v_campo_id, 'No', 'NO', 2, SYSDATE);

    -- Campo: Si responde sí, ¿Cuál?
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'TEXTO_CORTO', 
        'Si responde sí, ¿Cuál?', 'Especifique comunidad', 8, 'N', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    -- ========== SECCIÓN II: DATOS SOCIODEMOGRÁFICOS, ECONÓMICOS Y DE VIVIENDA ==========
    INSERT INTO IDO_FORMULARIO.CBTC_SECCIONES (
        ID_SECCION, ID_FORMULARIO, NO_TITULO, DE_DESCRIPCION, NU_ORDEN, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_SECCIONES.NEXTVAL,
        v_form_id,
        'II. DATOS SOCIODEMOGRÁFICOS, ECONÓMICOS Y DE VIVIENDA',
        'Datos del participante',
        2,
        SYSDATE,
        SYSDATE
    )
    RETURNING ID_SECCION INTO v_seccion_id;

    DBMS_OUTPUT.PUT_LINE('✅ Sección II creada con ID: ' || v_seccion_id);

    -- Campo 7: Estado civil
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_UNICA', 
        'Estado civil', 'Seleccione estado civil', 1, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Soltera', 'SOLTERA', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Casada', 'CASADA', 2, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Conviviente', 'CONVIVIENTE', 3, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Separada', 'SEPARADA', 4, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Viuda', 'VIUDA', 5, SYSDATE);

    -- Campo 8: Lengua materna
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FL_TIENE_OTRO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_UNICA', 
        'Lengua materna', 'Seleccione lengua materna', 2, 'S', 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Castellano', 'CASTELLANO', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Quechua', 'QUECHUA', 2, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Aymara', 'AYMARA', 3, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Asháninka', 'ASHANINKA', 4, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Shipibo', 'SHIPIBO', 5, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Awajun', 'AWAJUN', 6, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Otra', 'OTRA', 7, SYSDATE);

    -- Campo 9: ¿Entiende el castellano?
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_UNICA', 
        '¿Entiende el castellano?', 'Seleccione', 3, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Sí', 'SI', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Más o menos', 'MAS_O_MENOS', 2, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'No', 'NO', 3, SYSDATE);

    -- Campo 10: Nivel educativo alcanzado
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_UNICA', 
        'Nivel educativo alcanzado', 'Seleccione nivel educativo', 4, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Ninguno', 'NINGUNO', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Primaria incompleta', 'PRIMARIA_INCOMPLETA', 2, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Primaria completa', 'PRIMARIA_COMPLETA', 3, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Secundaria incompleta', 'SECUNDARIA_INCOMPLETA', 4, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Secundaria completa', 'SECUNDARIA_COMPLETA', 5, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Técnico', 'TECNICO', 6, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Superior universitaria', 'SUPERIOR_UNIVERSITARIA', 7, SYSDATE);

    -- Campo 11: Ocupación principal
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FL_TIENE_OTRO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_UNICA', 
        'Ocupación principal', 'Seleccione ocupación', 5, 'S', 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Ama de casa', 'AMA_DE_CASA', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Agricultora', 'AGRICULTORA', 2, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Vendedora', 'VENDEDORA', 3, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Artesana', 'ARTESANA', 4, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Otra', 'OTRA', 5, SYSDATE);

    -- ========== SECCIÓN III: DATOS DEL HOGAR ==========
    INSERT INTO IDO_FORMULARIO.CBTC_SECCIONES (
        ID_SECCION, ID_FORMULARIO, NO_TITULO, DE_DESCRIPCION, NU_ORDEN, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_SECCIONES.NEXTVAL,
        v_form_id,
        'III. DATOS DEL HOGAR',
        'Información del hogar',
        3,
        SYSDATE,
        SYSDATE
    )
    RETURNING ID_SECCION INTO v_seccion_id;

    DBMS_OUTPUT.PUT_LINE('✅ Sección III creada con ID: ' || v_seccion_id);

    -- Campo 12: Número total de personas que viven en el hogar
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, NU_MIN_VALOR, NU_MAX_VALOR, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'NUMERO', 
        'Número total de personas que viven en el hogar', 'Ingrese número', 1, 'S', 'S', 1, 50, SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    -- Campo 13: Número de niños/as menores de 5 años en el hogar
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, NU_MIN_VALOR, NU_MAX_VALOR, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'NUMERO', 
        'Número de niños/as menores de 5 años en el hogar', 'Ingrese número', 2, 'S', 'S', 0, 20, SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    -- Campo 14: Número de gestantes en el hogar
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, NU_MIN_VALOR, NU_MAX_VALOR, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'NUMERO', 
        'Número de gestantes en el hogar', 'Ingrese número', 3, 'S', 'S', 0, 10, SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    -- Campo 15: Tipo de familia
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FL_TIENE_OTRO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_UNICA', 
        'Tipo de familia', 'Seleccione tipo', 4, 'S', 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Nuclear (Papá, mamá, hijos)', 'NUCLEAR', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Extendida (Papá, mamá, hijos y otros familiares)', 'EXTENDIDA', 2, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Monoparental (mamá o papá soltero con sus hijos)', 'MONOPARENTAL', 3, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Otro', 'OTRO', 4, SYSDATE);

    -- ========== SECCIÓN IV: INGRESOS ECONÓMICOS Y PROGRAMAS SOCIALES ==========
    INSERT INTO IDO_FORMULARIO.CBTC_SECCIONES (
        ID_SECCION, ID_FORMULARIO, NO_TITULO, DE_DESCRIPCION, NU_ORDEN, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_SECCIONES.NEXTVAL,
        v_form_id,
        'IV. INGRESOS ECONÓMICOS Y PROGRAMAS SOCIALES',
        'Información económica y programas sociales',
        4,
        SYSDATE,
        SYSDATE
    )
    RETURNING ID_SECCION INTO v_seccion_id;

    DBMS_OUTPUT.PUT_LINE('✅ Sección IV creada con ID: ' || v_seccion_id);

    -- Campo 16: ¿Quién es el miembro del hogar que más contribuye con los gastos?
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_UNICA', 
        '¿Quién es el miembro del hogar que más contribuye con los gastos?', 'Seleccione', 1, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'La mamá', 'LA_MAMA', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'El papá', 'EL_PAPA', 2, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Otro familiar', 'OTRO_FAMILIAR', 3, SYSDATE);

    -- Campo 17: ¿Cuáles son tus fuentes principales de ingresos, además del Programa Juntos? (OPCION_MULTIPLE)
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FL_TIENE_OTRO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_MULTIPLE', 
        '¿Cuáles son tus fuentes principales de ingresos, además del Programa Juntos?', 'Seleccione todas las que apliquen', 2, 'N', 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Agricultura', 'AGRICULTURA', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Negocio personal', 'NEGOCIO_PERSONAL', 2, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Ganadería', 'GANADERIA', 3, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Actividades eventuales', 'ACTIVIDADES_EVENTUALES', 4, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Otro', 'OTRO', 5, SYSDATE);

    -- Campo 18: De cuánto dinero más o menos dispone la familia al mes para cubrir los gastos?
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_UNICA', 
        'De cuánto dinero más o menos dispone la familia al mes para cubrir los gastos?', 'Seleccione', 3, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'S/.______', 'MONTO_ESPECIFICO', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Solo incentivo Juntos', 'SOLO_INCENTIVO', 2, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'No precisa', 'NO_PRECISA', 3, SYSDATE);

    -- Campo 19: ¿Usted o algún otro miembro del Hogar participa de otro programa social, además de JUNTOS? (OPCION_MULTIPLE)
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FL_TIENE_OTRO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_MULTIPLE', 
        '¿Usted o algún otro miembro del Hogar participa de otro programa social, además de JUNTOS?', 'Seleccione todas las que apliquen', 4, 'N', 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Vaso de Leche', 'VASO_DE_LECHE', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Cuna Más', 'CUNA_MAS', 2, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Programa de alimentación escolar', 'ALIMENTACION_ESCOLAR', 3, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Pensión 65', 'PENSION_65', 4, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Otro', 'OTRO', 5, SYSDATE);

    -- ========== SECCIÓN V: CONDICIONES DE VIVIENDA ==========
    INSERT INTO IDO_FORMULARIO.CBTC_SECCIONES (
        ID_SECCION, ID_FORMULARIO, NO_TITULO, DE_DESCRIPCION, NU_ORDEN, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_SECCIONES.NEXTVAL,
        v_form_id,
        'V. CONDICIONES DE VIVIENDA',
        'Información sobre las condiciones de vivienda',
        5,
        SYSDATE,
        SYSDATE
    )
    RETURNING ID_SECCION INTO v_seccion_id;

    DBMS_OUTPUT.PUT_LINE('✅ Sección V creada con ID: ' || v_seccion_id);

    -- Campo 20: Tipo de vivienda
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_UNICA', 
        'Tipo de vivienda', 'Seleccione tipo', 1, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Material noble', 'MATERIAL_NOBLE', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Adobe', 'ADOBE', 2, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Madera', 'MADERA', 3, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Rústica', 'RUSTICA', 4, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Mixta', 'MIXTA', 5, SYSDATE);

    -- Campo 21: Tenencia de la vivienda
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_UNICA', 
        'Tenencia de la vivienda', 'Seleccione', 2, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Propia', 'PROPIA', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Alquilada', 'ALQUILADA', 2, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Cedida', 'CEDIDA', 3, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Ocupación informal (invasión)', 'OCUPACION_INFORMAL', 4, SYSDATE);

    -- Campo 22: Material del techo (OPCION_MULTIPLE)
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FL_TIENE_OTRO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_MULTIPLE', 
        'Material del techo', 'Seleccione todas las que apliquen', 3, 'S', 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Calamina', 'CALAMINA', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Eternit', 'ETERNIT', 2, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Teja', 'TEJA', 3, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Paja', 'PAJA', 4, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Otro', 'OTRO', 5, SYSDATE);

    -- Campo 23: Material del piso (OPCION_MULTIPLE)
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_MULTIPLE', 
        'Material del piso', 'Seleccione todas las que apliquen', 4, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Tierra', 'TIERRA', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Cemento', 'CEMENTO', 2, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Baldosa', 'BALDOSA', 3, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Madera', 'MADERA', 4, SYSDATE);

    -- Campo 24: ¿De dónde obtiene el agua para el consumo en su hogar? (OPCION_MULTIPLE)
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FL_TIENE_OTRO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_MULTIPLE', 
        '¿De dónde obtiene el agua para el consumo en su hogar?', 'Seleccione todas las que apliquen', 5, 'S', 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Red pública', 'RED_PUBLICA', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Río', 'RIO', 2, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Pozo comunal', 'POZO_COMUNAL', 3, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Camión cisterna', 'CAMION_CISTERNA', 4, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Bidón', 'BIDON', 5, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Río, canal, manantial', 'RIO_CANAL_MANANTIAL', 6, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Otro', 'OTRO', 7, SYSDATE);

    -- Campo 25: ¿Qué tipo de sistema de eliminación de excretas utilizan en el hogar?
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_UNICA', 
        '¿Qué tipo de sistema de eliminación de excretas utilizan en el hogar?', 'Seleccione', 6, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Red pública', 'RED_PUBLICA', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Letrina', 'LETRINA', 2, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Pozo séptico', 'POZO_SEPTICO', 3, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Silo', 'SILO', 4, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Aire libre', 'AIRE_LIBRE', 5, SYSDATE);

    -- Campo 26: ¿Cómo elimina la basura y residuos sólidos de su hogar? (OPCION_MULTIPLE)
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_MULTIPLE', 
        '¿Cómo elimina la basura y residuos sólidos de su hogar?', 'Seleccione todas las que apliquen', 7, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Recojo municipal (vehículo del municipio)', 'RECOJO_MUNICIPAL', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Quema', 'QUEMA', 2, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Entierra', 'ENTIERRA', 3, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Pozo', 'POZO', 4, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Aire libre', 'AIRE_LIBRE', 5, SYSDATE);

    -- Campo 27: ¿Utiliza algún técnica para obtener agua segura? (OPCION_MULTIPLE)
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FL_TIENE_OTRO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_MULTIPLE', 
        '¿Utiliza algún técnica para obtener agua segura?', 'Seleccione todas las que apliquen', 8, 'N', 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Hervido', 'HERVIDO', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Cloro', 'CLORO', 2, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Filtro', 'FILTRO', 3, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Otro', 'OTRO', 4, SYSDATE);

    -- ========== SECCIÓN VI: PARTICIPACIÓN Y ACCESO A SERVICIOS DE SALUD ==========
    INSERT INTO IDO_FORMULARIO.CBTC_SECCIONES (
        ID_SECCION, ID_FORMULARIO, NO_TITULO, DE_DESCRIPCION, NU_ORDEN, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_SECCIONES.NEXTVAL,
        v_form_id,
        'VI. PARTICIPACIÓN Y ACCESO A SERVICIOS DE SALUD',
        'Información sobre participación y servicios de salud',
        6,
        SYSDATE,
        SYSDATE
    )
    RETURNING ID_SECCION INTO v_seccion_id;

    DBMS_OUTPUT.PUT_LINE('✅ Sección VI creada con ID: ' || v_seccion_id);

    -- Campo 28: ¿Cuál es el tipo de seguro de Salud que tiene?
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_UNICA', 
        '¿Cuál es el tipo de seguro de Salud que tiene?', 'Seleccione', 1, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'SIS', 'SIS', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'EsSalud', 'ESSALUD', 2, SYSDATE);

    -- Campo 29: ¿Participa en alguna organización comunitaria? (OPCION_MULTIPLE)
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FL_TIENE_OTRO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_MULTIPLE', 
        '¿Participa en alguna organización comunitaria?', 'Seleccione todas las que apliquen', 2, 'N', 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Red de madres', 'RED_MADRES', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Comité de salud', 'COMITE_SALUD', 2, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Vaso de leche', 'VASO_DE_LECHE', 3, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'No participo', 'NO_PARTICIPO', 4, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Otro', 'OTRO', 5, SYSDATE);

    -- Campo 30: ¿Ha asistido o recibido orientación sobre anemia por parte del Centro de salud, Municipalidad, organización o Juntos, en los últimos 3 meses?
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_UNICA', 
        '¿Ha asistido o recibido orientación sobre anemia en los últimos 3 meses?', 'Seleccione', 3, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Sí', 'SI', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'No', 'NO', 2, SYSDATE);

    -- Campo 31: COMPROMISO Y REGISTRO AL PROGRAMA EDUCATIVO
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_UNICA', 
        '¿Se compromete a participar en sesiones educativas (3 meses semanales) y acepta llamadas de acompañamiento para prevenir anemia?', 'Seleccione', 4, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'SI confirmo', 'SI_CONFIRMO', 1, SYSDATE);

    -- Campo 32: ¿Cuál es tu preferencia de horario para asistir a las sesiones educativas?
    INSERT INTO IDO_FORMULARIO.CBTC_CAMPOS (
        ID_CAMPO, ID_SECCION, CO_TIPO, NO_LABEL, DE_PLACEHOLDER, NU_ORDEN, 
        FL_OBLIGATORIO, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION
    )
    VALUES (
        IDO_FORMULARIO.CBSE_CAMPOS.NEXTVAL, v_seccion_id, 'OPCION_UNICA', 
        '¿Cuál es tu preferencia de horario para asistir a las sesiones educativas?', 'Seleccione', 5, 'S', 'S', SYSDATE, SYSDATE
    )
    RETURNING ID_CAMPO INTO v_campo_id;

    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Mañanas', 'MANANAS', 1, SYSDATE);
    INSERT INTO IDO_FORMULARIO.CBTC_OPCIONES_CAMPOS (ID_CAMPO, NO_TEXTO, DE_VALOR, NU_ORDEN, FE_CREACION) VALUES (v_campo_id, 'Tardes', 'TARDES', 2, SYSDATE);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('✅✅✅ FORMULARIO COMPLETO CREADO EXITOSAMENTE ✅✅✅');
    DBMS_OUTPUT.PUT_LINE('Formulario ID: ' || v_form_id);
    DBMS_OUTPUT.PUT_LINE('Total de secciones: 7');
    DBMS_OUTPUT.PUT_LINE('Total de campos: 32+');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('❌ ERROR: ' || SQLERRM);
        RAISE;
END;
/

