-- Script para recrear limpiamente las tablas de usuarios, productos y roles
-- Esquema: IDO_FORMULARIO
-- Usuario: IDO_FORMULARIO
-- Clave: MFLstcIII4#
--
-- IMPORTANTE: Este script ELIMINA y RECREA las tablas de usuarios y productos
-- Ejecutar con precaución - se perderán todos los datos existentes
--
-- Ejemplo de conexión:
--   sqlplus IDO_FORMULARIO/MFLstcIII4#@192.168.125.181:1521/juntosdv
--   @recreate_usuarios_productos_roles.sql

SET SERVEROUTPUT ON;

-- ============================================
-- ELIMINAR TRIGGERS
-- ============================================

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER IDO_FORMULARIO.TRG_PRODUCTOS_ACTUALIZACION';
    DBMS_OUTPUT.PUT_LINE('✅ Trigger TRG_PRODUCTOS_ACTUALIZACION eliminado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -4080 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️  Trigger TRG_PRODUCTOS_ACTUALIZACION no existe (ignorado)');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER IDO_FORMULARIO.TRG_ROLES_ACTUALIZACION';
    DBMS_OUTPUT.PUT_LINE('✅ Trigger TRG_ROLES_ACTUALIZACION eliminado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -4080 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️  Trigger TRG_ROLES_ACTUALIZACION no existe (ignorado)');
        ELSE
            RAISE;
        END IF;
END;
/

-- ============================================
-- ELIMINAR ÍNDICES
-- ============================================

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDO_FORMULARIO.IDX_PRODUCTOS_FE_ACTUALIZACION';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDO_FORMULARIO.IDX_PRODUCTOS_NO_PRODUCTO';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDO_FORMULARIO.IDX_PRODUCTOS_FE_CREACION';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDO_FORMULARIO.IDX_USUARIOS_FE_CREACION';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDO_FORMULARIO.IDX_USUARIOS_ROL';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDO_FORMULARIO.IDX_ROLES_ACTIVO';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- ============================================
-- ELIMINAR TABLAS (en orden de dependencias)
-- ============================================

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE IDO_FORMULARIO.CBTC_PRODUCTOS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✅ Tabla CBTC_PRODUCTOS eliminada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -942 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️  Tabla CBTC_PRODUCTOS no existe (ignorado)');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE IDO_FORMULARIO.CBTC_USUARIOS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✅ Tabla CBTC_USUARIOS eliminada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -942 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️  Tabla CBTC_USUARIOS no existe (ignorado)');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE IDO_FORMULARIO.CBTC_ROLES CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✅ Tabla CBTC_ROLES eliminada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -942 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️  Tabla CBTC_ROLES no existe (ignorado)');
        ELSE
            RAISE;
        END IF;
END;
/

-- ============================================
-- ELIMINAR SECUENCIAS
-- ============================================

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE IDO_FORMULARIO.CBSE_PRODUCTOS';
    DBMS_OUTPUT.PUT_LINE('✅ Secuencia CBSE_PRODUCTOS eliminada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -2289 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️  Secuencia CBSE_PRODUCTOS no existe (ignorado)');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE IDO_FORMULARIO.CBSE_USUARIOS';
    DBMS_OUTPUT.PUT_LINE('✅ Secuencia CBSE_USUARIOS eliminada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -2289 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️  Secuencia CBSE_USUARIOS no existe (ignorado)');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE IDO_FORMULARIO.CBSE_ROLES';
    DBMS_OUTPUT.PUT_LINE('✅ Secuencia CBSE_ROLES eliminada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -2289 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️  Secuencia CBSE_ROLES no existe (ignorado)');
        ELSE
            RAISE;
        END IF;
END;
/

COMMIT;

-- ============================================
-- CREAR SECUENCIAS
-- ============================================

-- Secuencia para roles (debe crearse primero)
CREATE SEQUENCE IDO_FORMULARIO.CBSE_ROLES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para usuarios
CREATE SEQUENCE IDO_FORMULARIO.CBSE_USUARIOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para productos
CREATE SEQUENCE IDO_FORMULARIO.CBSE_PRODUCTOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

DBMS_OUTPUT.PUT_LINE('✅ Secuencias creadas');

-- ============================================
-- CREAR TABLAS
-- ============================================

-- Tabla maestra de roles (debe crearse primero)
CREATE TABLE IDO_FORMULARIO.CBTC_ROLES (
    ID_ROL NUMBER DEFAULT IDO_FORMULARIO.CBSE_ROLES.NEXTVAL PRIMARY KEY,
    NO_ROL VARCHAR2(50) NOT NULL UNIQUE, -- ADMINISTRADOR, GESTOR_LOCAL, etc.
    DE_DESCRIPCION VARCHAR2(200),
    FL_ACTIVO CHAR(1) DEFAULT 'S' NOT NULL, -- S/N
    FE_CREACION DATE DEFAULT SYSDATE NOT NULL,
    FE_ACTUALIZACION DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CHK_ACTIVO_ROL CHECK (FL_ACTIVO IN ('S', 'N'))
);

COMMENT ON TABLE IDO_FORMULARIO.CBTC_ROLES IS 'Tabla maestra de roles del sistema';
COMMENT ON COLUMN IDO_FORMULARIO.CBTC_ROLES.ID_ROL IS 'Identificador único del rol';
COMMENT ON COLUMN IDO_FORMULARIO.CBTC_ROLES.NO_ROL IS 'Nombre del rol (ADMINISTRADOR, GESTOR_LOCAL, etc.)';
COMMENT ON COLUMN IDO_FORMULARIO.CBTC_ROLES.DE_DESCRIPCION IS 'Descripción del rol y sus permisos';
COMMENT ON COLUMN IDO_FORMULARIO.CBTC_ROLES.FL_ACTIVO IS 'Indica si el rol está activo (S/N)';

-- Tabla de usuarios (con columna de rol)
CREATE TABLE IDO_FORMULARIO.CBTC_USUARIOS (
    ID_USUARIO NUMBER DEFAULT IDO_FORMULARIO.CBSE_USUARIOS.NEXTVAL PRIMARY KEY,
    NO_USERNAME VARCHAR2(50) NOT NULL,
    CO_PASSWORD_HASH VARCHAR2(255) NOT NULL,
    DI_CORREO VARCHAR2(100) NOT NULL,
    CO_OFFLINE_PASSWORD VARCHAR2(32),
    ID_ROL NUMBER, -- FK a CBTC_ROLES
    FE_CREACION TIMESTAMP DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UK_USUARIOS_USERNAME UNIQUE (NO_USERNAME),
    CONSTRAINT UK_USUARIOS_CORREO UNIQUE (DI_CORREO),
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ID_ROL) 
        REFERENCES IDO_FORMULARIO.CBTC_ROLES(ID_ROL)
);

COMMENT ON TABLE IDO_FORMULARIO.CBTC_USUARIOS IS 'Tabla de usuarios del sistema';
COMMENT ON COLUMN IDO_FORMULARIO.CBTC_USUARIOS.ID_USUARIO IS 'Identificador único del usuario';
COMMENT ON COLUMN IDO_FORMULARIO.CBTC_USUARIOS.NO_USERNAME IS 'Nombre de usuario único';
COMMENT ON COLUMN IDO_FORMULARIO.CBTC_USUARIOS.CO_PASSWORD_HASH IS 'Contraseña hasheada (BCrypt)';
COMMENT ON COLUMN IDO_FORMULARIO.CBTC_USUARIOS.DI_CORREO IS 'Correo electrónico del usuario';
COMMENT ON COLUMN IDO_FORMULARIO.CBTC_USUARIOS.CO_OFFLINE_PASSWORD IS 'Contraseña MD5 para login offline';
COMMENT ON COLUMN IDO_FORMULARIO.CBTC_USUARIOS.ID_ROL IS 'Rol del usuario (FK a CBTC_ROLES)';

-- Tabla de productos
CREATE TABLE IDO_FORMULARIO.CBTC_PRODUCTOS (
    ID_PRODUCTO NUMBER DEFAULT IDO_FORMULARIO.CBSE_PRODUCTOS.NEXTVAL PRIMARY KEY,
    NO_PRODUCTO VARCHAR2(30) NOT NULL,
    ME_PRECIO NUMBER(10, 2) NOT NULL,
    CA_CANTIDAD NUMBER NOT NULL,
    FE_CREACION TIMESTAMP DEFAULT SYSDATE NOT NULL,
    FE_ACTUALIZACION TIMESTAMP DEFAULT SYSDATE NOT NULL
);

COMMENT ON TABLE IDO_FORMULARIO.CBTC_PRODUCTOS IS 'Tabla de productos del sistema';
COMMENT ON COLUMN IDO_FORMULARIO.CBTC_PRODUCTOS.ID_PRODUCTO IS 'Identificador único del producto';
COMMENT ON COLUMN IDO_FORMULARIO.CBTC_PRODUCTOS.NO_PRODUCTO IS 'Nombre del producto (máximo 30 caracteres)';
COMMENT ON COLUMN IDO_FORMULARIO.CBTC_PRODUCTOS.ME_PRECIO IS 'Precio del producto';
COMMENT ON COLUMN IDO_FORMULARIO.CBTC_PRODUCTOS.CA_CANTIDAD IS 'Cantidad disponible del producto';
COMMENT ON COLUMN IDO_FORMULARIO.CBTC_PRODUCTOS.FE_CREACION IS 'Fecha de creación del producto';
COMMENT ON COLUMN IDO_FORMULARIO.CBTC_PRODUCTOS.FE_ACTUALIZACION IS 'Fecha de última actualización del producto';

DBMS_OUTPUT.PUT_LINE('✅ Tablas creadas');

-- ============================================
-- INSERTAR DATOS INICIALES (ROLES)
-- ============================================

-- Insertar rol ADMINISTRADOR
INSERT INTO IDO_FORMULARIO.CBTC_ROLES (ID_ROL, NO_ROL, DE_DESCRIPCION, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION)
VALUES (IDO_FORMULARIO.CBSE_ROLES.NEXTVAL, 'ADMINISTRADOR', 'Administrador del sistema. Puede crear, editar y eliminar formularios. Acceso completo al sistema.', 'S', SYSDATE, SYSDATE);

-- Insertar rol GESTOR_LOCAL
INSERT INTO IDO_FORMULARIO.CBTC_ROLES (ID_ROL, NO_ROL, DE_DESCRIPCION, FL_ACTIVO, FE_CREACION, FE_ACTUALIZACION)
VALUES (IDO_FORMULARIO.CBSE_ROLES.NEXTVAL, 'GESTOR_LOCAL', 'Gestor Local. Puede ver y llenar formularios. Puede responder múltiples veces el mismo formulario.', 'S', SYSDATE, SYSDATE);

DBMS_OUTPUT.PUT_LINE('✅ Roles iniciales insertados');

-- ============================================
-- CREAR ÍNDICES
-- ============================================

-- Índices para roles
CREATE INDEX IDO_FORMULARIO.IDX_ROLES_ACTIVO ON IDO_FORMULARIO.CBTC_ROLES(FL_ACTIVO);

-- Índices para usuarios
CREATE INDEX IDO_FORMULARIO.IDX_USUARIOS_FE_CREACION ON IDO_FORMULARIO.CBTC_USUARIOS(FE_CREACION);
CREATE INDEX IDO_FORMULARIO.IDX_USUARIOS_ROL ON IDO_FORMULARIO.CBTC_USUARIOS(ID_ROL);

-- Índices para productos
CREATE INDEX IDO_FORMULARIO.IDX_PRODUCTOS_FE_CREACION ON IDO_FORMULARIO.CBTC_PRODUCTOS(FE_CREACION);
CREATE INDEX IDO_FORMULARIO.IDX_PRODUCTOS_FE_ACTUALIZACION ON IDO_FORMULARIO.CBTC_PRODUCTOS(FE_ACTUALIZACION);
CREATE INDEX IDO_FORMULARIO.IDX_PRODUCTOS_NO_PRODUCTO ON IDO_FORMULARIO.CBTC_PRODUCTOS(NO_PRODUCTO);

DBMS_OUTPUT.PUT_LINE('✅ Índices creados');

-- ============================================
-- CREAR TRIGGERS
-- ============================================

-- Trigger para actualizar FE_ACTUALIZACION en CBTC_ROLES
CREATE OR REPLACE TRIGGER IDO_FORMULARIO.TRG_ROLES_ACTUALIZACION
BEFORE UPDATE ON IDO_FORMULARIO.CBTC_ROLES
FOR EACH ROW
BEGIN
    :NEW.FE_ACTUALIZACION := SYSDATE;
END;
/

-- Trigger para actualizar FE_ACTUALIZACION en CBTC_PRODUCTOS
CREATE OR REPLACE TRIGGER IDO_FORMULARIO.TRG_PRODUCTOS_ACTUALIZACION
BEFORE UPDATE ON IDO_FORMULARIO.CBTC_PRODUCTOS
FOR EACH ROW
BEGIN
    :NEW.FE_ACTUALIZACION := SYSDATE;
END;
/

DBMS_OUTPUT.PUT_LINE('✅ Triggers creados');

COMMIT;

-- ============================================
-- VERIFICACIÓN
-- ============================================

SELECT '✅ Esquema recreado exitosamente' AS mensaje FROM DUAL;

-- Mostrar roles creados
SELECT 'Roles creados:' AS info FROM DUAL;
SELECT ID_ROL, NO_ROL, DE_DESCRIPCION, FL_ACTIVO FROM IDO_FORMULARIO.CBTC_ROLES;

-- Mostrar estructura de tablas
SELECT 'Tablas creadas:' AS info FROM DUAL;
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN ('CBTC_ROLES', 'CBTC_USUARIOS', 'CBTC_PRODUCTOS') ORDER BY TABLE_NAME;

SELECT '✅ Script completado exitosamente' AS mensaje FROM DUAL;

